from typing import List, Optional, Union, Callable
import torch

# Default parameters for UnbiasedDiseasePipeline
PROMPT = None
HEIGHT = 1024
WIDTH = 1024
NUM_INFERENCE_STEPS = 50
GUIDANCE_SCALE = 7.5
NEGATIVE_PROMPT = None
NUM_IMAGES_PER_PROMPT = 1
ETA = 0.0
GENERATOR = None
LATENTS = None
OUTPUT_TYPE = "pil"
RETURN_DICT = True
CALLBACK = None
CALLBACK_STEPS = 1
EDITING_PROMPT = None
EDITING_PROMPT_PROMPT_EMBEDDINGS = None
REVERSE_EDITING_DIRECTION = False
EDIT_GUIDANCE_SCALE = 500
EDIT_WARMUP_STEPS = 10
EDIT_COOLDOWN_STEPS = None
EDIT_THRESHOLD = None
EDIT_MOMENTUM_SCALE = 0.1
EDIT_MOM_BETA = 0.4
EDIT_WEIGHTS = None
SEM_GUIDANCE = None
